<a href="https://colab.research.google.com/github/LucianoLarrea/LucianoLarrea/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Conceptos fundamentales de TensorFlow:
# Introduccion a Tensores
# Obtener informacion de tensores
# Manipular tensores
# Tensores y Numpy
# Usar tf.function para acelerar funciones de Python
# Usar GPU con TensorFlow
# Ejercicios para autotest

# Introduccion a Tensores

In [ ]:
# Importar Tensorflow
import tensorflow as tf
print (tf.__version__)

2.7.0


In [ ]:
# Crear tensores con tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Chequear el numero de dimensiones de un tensor
scalar.ndim


0

In [ ]:
#Crear un vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Verificar dimensiones del vector
vector.ndim

1

In [ ]:
#Crear una matriz
matriz = tf.constant([[10,7],[3,8]])
matriz

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  8]], dtype=int32)>

In [ ]:
matriz.ndim

2

In [ ]:

#Crear matriz especificando el tipo de datos como Float
matriz2 = tf.constant([[10.,7.],[3.,8.],[1.,2.]], dtype=tf.float16)
matriz2


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  8.],
       [ 1.,  2.]], dtype=float16)>

In [ ]:
#El numero de dimensiones es la cantidad de elementos que hay en shape=()
matriz2.ndim

2

In [ ]:
#Crear un tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Tipos de tensores
#Scalar = una magnitud constante
#Vector = una magnitud con direccion
#Matriz = una formacion de numeros de 2-direcciones
#Tensor = una formacion de numeros de n-direcciones


Crear tensores con tf.variable

In [ ]:
#Crear el mismo tensor con tf.variable
tensor_editable = tf.Variable([10,10])
tensor_no_editable = tf.constant([10,10])
tensor_editable,tensor_no_editable


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

Probemos editar el tensor redefiniendo su valor

In [ ]:
tensor_editable[0] = 7
tensor_editable

TypeError: ignored

Probemos editar el tensor con la funcion assign

In [ ]:
tensor_editable[0].assign(7)
tensor_editable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Probemos editar el tensor no editable

In [ ]:
tensor_no_editable[0].assign(7)
tensor_no_editable

AttributeError: ignored

Crear Tensores aleatorios
Primero crear 2 tensores aleatorios iguales

In [ ]:
random_1 = tf.random.Generator.from_seed(42) #Seed permite reproducir
random_1 = random_1.normal(shape=[3,2])
random_2 = tf.random.Generator.from_seed(42) #Otro tensor aleatorio con la misma Seed
random_2 = random_2.normal(shape=[3,2])
random_1, random_2, random_1 == random_2 #Son iguales?

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Mezclar los elementos de un tensor

In [ ]:
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
not_shuffled.ndim

2

In [ ]:
#Vamos a mezclar el tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)                    #Global level seed
tf.random.shuffle(not_shuffled, seed=42)  #Operations level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
#Crear un tensor de unos
tf.ones([3,4])


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Crear un tensor de ceros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Convertir un arreglo NumPy en un Tensor (los tensores pueden correrse mas rapido en un GPU que lo array)

In [ ]:
import numpy as np
numpy_A = np.arange (1,25, dtype = np.int32) #Crear un numpy array entre 1 y 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A) #Tensor de una dimension = Vector
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape=(2,3,4)) #Tensor de 3 dimensiones donde 2x3x4 = 24
B


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
C = tf.constant(numpy_A, shape=(8,3)) #Tensor de 2 dimensiones donde 8x3 = 24
C

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

Obtener informacion de los tensores
Shape
Ejes o Dimensiones
Rank
Size

In [ ]:
#Crear un Tensor Rank 4 (4 dimensiones)
Rank_4 = tf.ones(shape = [2,2,3,4])
Rank_4

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
Rank_4[0]


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
Rank_4.shape, Rank_4.ndim, tf.size(Rank_4)

(TensorShape([2, 2, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [ ]:
2*2*3*4


48

In [ ]:
#Obtener datos de un tensor
print("Tipo de datos de cada elemento:",Rank_4.dtype)
print("Numero de dimensiones:",Rank_4.ndim)
print("Forma del tensor:",Rank_4.shape)
print("Elementos en el eje 0:",Rank_4.shape[0])
print("Elementos en el ultimo eje:",Rank_4.shape[-1])
print("Numero total de elementos:",tf.size(Rank_4).numpy())


Tipo de datos de cada elemento: <dtype: 'float32'>
Numero de dimensiones: 4
Forma del tensor: (2, 2, 3, 4)
Elementos en el eje 0: 2
Elementos en el ultimo eje: 4
Numero total de elementos: 48


Indexar Tensores
Los tensores pueden indexarse como las Listas de Python

In [ ]:
from typing import List
#Obtener los primeros 2 elementos de cada dimension
List = [1,2,3,4] #Ejemplo
List [:2]

[1, 2]

In [ ]:
Rank_4 [:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
#Obtener el primer elemento de cada dimension exceptuando la ultima dimension
Rank_4 [:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
#Agregar una nueva dimension
Rank_5 = Rank_4[...,tf.newaxis]
Rank_5


<tf.Tensor: shape=(2, 2, 3, 4, 1), dtype=float32, numpy=
array([[[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]],



       [[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]]], dtype=float32)>

In [ ]:
#Alternativa a tf.newaxis
tf.expand_dims(Rank_4,axis=-1) #-1 significa que debe expandir la ultima dimension

<tf.Tensor: shape=(2, 2, 3, 4, 1), dtype=float32, numpy=
array([[[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]],



       [[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]]], dtype=float32)>

Operaciones de Tensores (Manipulacion)
Operaciones Basicas

In [ ]:
Tensor = tf.constant([[1,2],[3,4]])  #Le sumo 10
Tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
#El tensor original no cambio
Tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Multiplicacion de matrices(mas usada en TensorFlow)


In [ ]:
print(Tensor)
tf.matmul(Tensor,Tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
#Se puede multiplicar matrices con el operador de Python @
Tensor @ Tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
#Hay reglas en la multiplicacion de matrices: las dimensiones internas deben coincidir y las dimensiones externas determinan las dimensiones de la matriz resultante


In [ ]:
X = Tensor                              #X es una matriz de 2x2
Y = tf.constant([[2,3],
                 [4,5],
                 [6,7]])    #Y es una matriz de 3x2
X @ Y

InvalidArgumentError: ignored

In [ ]:
#Vamos a cambiar la forma de Y para que sean compatbles para multiplicacion
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 15, 18],
       [26, 33, 40]], dtype=int32)>

In [ ]:
# Se pueden trasponer las matrices o cambiar la forma, el resultado no es exactamente el mismo
print("Matriz original:",Y) , print("Matriz traspuesta: ",tf.transpose(Y)), print("Reshape de matriz:",tf.reshape(Y, shape=(2, 3)))


Matriz original: tf.Tensor(
[[2 3]
 [4 5]
 [6 7]], shape=(3, 2), dtype=int32)
Matriz traspuesta:  tf.Tensor(
[[2 4 6]
 [3 5 7]], shape=(2, 3), dtype=int32)
Reshape de matriz: tf.Tensor(
[[2 3 4]
 [5 6 7]], shape=(2, 3), dtype=int32)


(None, None, None)

In [ ]:
#Probemos multiplicar usando Transpose y veamos que difiere de la multiplicacion usando Reshape
X @ tf.transpose(Y),X @ tf.reshape(Y, shape=(2, 3))


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 8, 14, 20],
        [18, 32, 46]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[12, 15, 18],
        [26, 33, 40]], dtype=int32)>)

Por lo general se utiliza Trasponer matriz para hacer una multiplicacion compatible

Cambiar los tipos de datos del tensor

In [ ]:
B = tf.constant([1.2,2.3])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [ ]:
#Cambiar de Float32 a Float16 para ahorrar procesamiento de calculo
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 2.3], dtype=float16)>

Agregacion de tensores: Condensar de multiples valores a una pequenia cantidad de valores por ejemplo
Valor Absoluto
Minimo y Maximo
Suma y Mediana

In [ ]:
#Valor Absoluto
E = tf.constant([-1,-2])
tf.abs(E)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
#Crear un Tensor aleatrorio con valores entre 0 y 100 de tamanio 50
F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([75, 28, 22, 39, 73,  0, 13, 72, 42, 19, 32, 30, 98, 22, 51, 67, 85,
       79, 29, 97, 45, 46, 51, 56, 39, 52, 53, 42, 13, 84, 34, 13, 60, 85,
       25, 39, 60, 15,  3, 56, 12, 65,  4, 24, 26, 25, 53, 40, 89, 42])>

In [ ]:
tf.size(F),F.shape,F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Encontrar el minimo, maximo, mediana y suma
tf.reduce_min(F),tf.reduce_max(F),tf.reduce_mean(F),tf.reduce_sum(F)


(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2224>)

In [ ]:
#Para obtener la varianza y la desviacion estandar debo importar tensorflow_probability 
import tensorflow_probability as tfp
tfp.stats.variance(F) #Varianza

<tf.Tensor: shape=(), dtype=int64, numpy=653>

In [ ]:
tfp.stats.stddev(F) #Desvio estandar

InvalidArgumentError: ignored

In [ ]:
tfp.stats.stddev(tf.cast(F,dtype=tf.float16)) #Desvio estandar cambiando a float

<tf.Tensor: shape=(), dtype=float16, numpy=25.55>

In [ ]:
#Tambien lo puedo hacer sin importat tensorflow_probability utilizando tf.math
tf.math.reduce_variance(tf.cast(F,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=653.0>

Encontrar la posicion del maximo y del minimo

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
from functools import reduce
#Posicion del maximo , valor del maximo , chequear si coinciden
tf.argmax(G) , tf.reduce_max(G) , G[tf.argmax(G)] == tf.reduce_max(G)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [ ]:
#Posicion del minimo , valor del minimo , chequear si coinciden
tf.argmin(G) , tf.reduce_min(G) , G[tf.argmin(G)] == tf.reduce_min(G)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

Remover dimensiones simples de un tensor

In [ ]:
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
H_squeezed = tf.squeeze(H)
H_squeezed.shape

TensorShape([50])

In [ ]:
#One-hot encoding tensors
#Crear una lista de indices
lista = [1,2,3,4]
#One-hot encoding
tf.one_hot(lista,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Especificar valores para One-hot
tf.one_hot(lista,depth=4,on_value="Luccio",off_value="-")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'-', b'Luccio', b'-', b'-'],
       [b'-', b'-', b'Luccio', b'-'],
       [b'-', b'-', b'-', b'Luccio'],
       [b'-', b'-', b'-', b'-']], dtype=object)>

Potencia al cuadrado, raiz cuadrada y logaritmo

In [ ]:
#Nuevo tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Tensor al cuadrado
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Raiz cuadrada
tf.sqrt(tf.cast(H,dtype=float))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Logaritmo
tf.math.log(tf.cast(H,dtype=float))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors y NumPy: TensorFlow interactua muy bien con los arreglos de NumPy

In [ ]:
#Crear un Tensor directamente desde una matriz NumPy
J = tf.constant(np.array([1.,2.,3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
#Convertir el tensor en una matriz NumPy
np.array(J), type(np.array(J))

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
#Tambien se puede usar 
J.numpy(), type(np.array(J))

(array([1., 2., 3.]), numpy.ndarray)